name: buildAndPush

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - run: go mod tidy
    - run: go mod download
    - run: go build -o integration-tests .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr
    - run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/mensaje-service-tests:${{ github.sha }} .
        docker build -t ${{ steps.login-ecr.outputs.registry }}/mensaje-service-tests:latest .
        docker push ${{ steps.login-ecr.outputs.registry }}/mensaje-service-tests:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/mensaje-service-tests:latest
